environment:
  global:
    WEBOTS_HOME_PROTECTED: "/C/projects/webots"
    WEBOTS_HOME: "C:\\projects\\webots"

  matrix:
    - compiler: msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64

install:
  - C:\\msys64\\usr\\bin\\pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
  - C:\\msys64\\usr\\bin\\pacman --noconfirm -S --noconfirm git mingw-w64-x86_64-cppcheck
  - pip install -r %APPVEYOR_BUILD_FOLDER%/tests/sources/requirements.txt
  - pip install -r %APPVEYOR_BUILD_FOLDER%/docs/tests/requirements.txt

build: off

test_script:
  - C:\\msys64\\usr\\bin\\bash --login -c "python -m unittest discover -s %WEBOTS_HOME_PROTECTED%/docs/tests"
  - ps: if ($env:APPVEYOR_SCHEDULED_BUILD -ne "True" -and $env:APPVEYOR_PULL_REQUEST_NUMBER -ge 1) { C:\\msys64\\usr\\bin\\bash --login -c "python $env:WEBOTS_HOME_PROTECTED/tests/sources/generate_diff.py $env:APPVEYOR_REPO_COMMIT $env:APPVEYOR_REPO_NAME" }
  - ps: Write-Host "$env:APPVEYOR_REPO_COMMIT $env:APPVEYOR_REPO_NAME"
  - ps: Get-Content -path $env:WEBOTS_HOME_PROTECTED\tests\sources\dump.txt
  - ps: Get-Content -path $env:WEBOTS_HOME_PROTECTED\tests\sources\modified_files.txt
  - C:\\msys64\\usr\\bin\\bash --login -c "python -m unittest discover -s %WEBOTS_HOME_PROTECTED%/tests/sources"
