# This file is used by the "webots-test-sources-master" and "webots-test-sources-develop" appveyor projects.

clone_depth: 1

install:
  - set PATH=C:\Python38-x64;C:\Python38-x64\Scripts;C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH%
  - bash -lc "echo 'Server = https://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/' > /etc/pacman.d/mirrorlist.mingw64"
  - bash -lc "echo 'Server = https://sourceforge.net/projects/msys2/files/REPOS/MINGW/i686/' > /etc/pacman.d/mirrorlist.mingw32"
  - bash -lc "echo 'Server = https://sourceforge.net/projects/msys2/files/REPOS/MSYS2/$arch/' > /etc/pacman.d/mirrorlist.msys"
  - bash -lc "curl -O https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  - bash -lc "curl -O https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
  - bash -lc "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
  - bash -lc "pacman -U --noconfirm msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  - bash -lc "pacman -Syu --noconfirm"
  - taskkill /f /fi "MODULES eq msys-2.0.dll"
  - pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
  - pacman --noconfirm -Syuu
  - pacman --noconfirm -S mingw-w64-x86_64-cppcheck
  - pacman --noconfirm -S mingw-w64-x86_64-clang
  - pip install -r %APPVEYOR_BUILD_FOLDER%\\tests\\sources\\requirements.txt
  - pip install -r %APPVEYOR_BUILD_FOLDER%\\docs\\tests\\requirements.txt
  - copy %APPVEYOR_BUILD_FOLDER%\\dependencies\\.clang-format-9 %APPVEYOR_BUILD_FOLDER%\\.clang-format

build: off

test_script:
  - set WEBOTS_HOME=%APPVEYOR_BUILD_FOLDER%
  - python -m unittest discover -s %APPVEYOR_BUILD_FOLDER%\\docs\\tests
  - python -m unittest discover -s %APPVEYOR_BUILD_FOLDER%\\tests\\sources
