# This file is used by the "webots-test-sources" appveyor project.

branches:
  except:
    - develop
    - revision
    - master

clone_depth: 1

install:
  - set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH%
  - pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
  - pacman --noconfirm -Syuu
  - pacman --noconfirm -S mingw-w64-x86_64-cppcheck
  - pacman --noconfirm -S mingw-w64-x86_64-clang
  - pip install -r %APPVEYOR_BUILD_FOLDER%\\tests\\sources\\requirements.txt
  - pip install -r %APPVEYOR_BUILD_FOLDER%\\docs\\tests\\requirements.txt
  - copy %APPVEYOR_BUILD_FOLDER%\\dependencies\\.clang-format-9 %APPVEYOR_BUILD_FOLDER%\\.clang-format

build: off

test_script:
  - set WEBOTS_HOME=%APPVEYOR_BUILD_FOLDER%
  - python -m unittest discover -s %APPVEYOR_BUILD_FOLDER%\\docs\\tests
  - ps: if ($env:APPVEYOR_REPO_TAG -ne "true") { python $env:APPVEYOR_BUILD_FOLDER\\tests\\sources\\generate_diff.py $env:APPVEYOR_REPO_COMMIT $env:APPVEYOR_REPO_NAME }
  - python -m unittest discover -s %APPVEYOR_BUILD_FOLDER%\\tests\\sources
