environment:
  matrix:
    - compiler: msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64

clone_depth: 1

init:
  # The following line will display the login information for a remote desktop connection (useful to debug)
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;C:\msys64\usr\bin;%PATH%

install:
  - pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
  - pacman --noconfirm -Syuu
  - bash --login -c "echo export JAVA_HOME=\\\"/C/Program\ Files/Java/jdk1.8.0\\\" >> ~/.bash_profile"
  - bash --login -c "echo export PYTHON27_HOME=/C/Python27-x64 >> ~/.bash_profile"
  - bash --login -c "echo export PYTHON37_HOME=/C/Python37-x64 >> ~/.bash_profile"
  - bash --login -c "echo export VISUAL_STUDIO_PATH=\\\"/C/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio\ 10.0\\\" >> ~/.bash_profile"
  - bash --login -c "echo export INNO_SETUP_HOME=\\\"/C/Program\ Files\ \(x86\)/Inno\ Setup\ 6\\\" >> ~/.bash_profile"
  - bash --login -c "echo export PATH=\\\"$PYTHON37_HOME:$PYTHON37_HOME/Scripts:$WEBOTS_HOME_PROTECTED/msys64/mingw64/bin:/mingw64/bin:/usr/bin:$JAVA_HOME/bin:/c/WINDOWS/system32:/c/WINDOWS\\\" >> ~/.bash_profile"
  - bash --login -c "echo export WEBOTS_HOME=\\\"%APPVEYOR_BUILD_FOLDER%\\\" >> ~/.bash_profile"
  - bash --login -c "echo export WEBOTS_HOME_PATH=`echo \"$WEBOTS_HOME\" | sed 's/\\\\/\\//g' | sed 's/://'`" >> ~/.bash_profile
  - ps: Start-Sleep -s 3600
  - bash --login -c "cd $WEBOTS_HOME_PATH; git submodule init; git submodule update"
  - bash --login -c "$WEBOTS_HOME_PATH/src/install_scripts/msys64_installer.sh --all"
  - bash --login -c "$WEBOTS_HOME_PATH/src/install_scripts/inno_setup_installer.sh"
  # - bash --login -c "pip install -r $WEBOTS_HOME_PATH/tests/sources/requirements.txt"
  # - bash --login -c "pip install -r $WEBOTS_HOME_PATH/docs/tests/requirements.txt"
  - bash --login -c "pip install PyGithub"
  # The following line make the session on the virtual machine last some time to allow remote desktop session debugging 
  # - ps: Start-Sleep -s 3600

build_script:
  - ps: if ($env:APPVEYOR_SCHEDULED_BUILD -eq "True" -and $env:APPVERYOR_TAG -ne "true") { python $env:APPVEYOR_BUILD_FOLDER\\src\\packaging\\set_commit_and_date_in_version.py $env:APPVEYOR_REPO_COMMIT }
  - ps: if ($env:APPVEYOR_SCHEDULED_BUILD -eq "True") { bash --login -c "cd $WEBOTS_HOME_PATH; make distrib -j4" }
  - ps: if ($env:APPVEYOR_SCHEDULED_BUILD -eq "True") { python $env:APPVEYOR_BUILD_FOLDER\\src\\packaging\\publish_release.py --key=$env:GITHUB_API_KEY --repo=$env:APPVEYOR_REPO_NAME --branch=$env:APPVEYOR_REPO_BRANCH --commit=$env:APPVEYOR_REPO_COMMIT --tag=$env:APPVEYOR_REPO_TAG_NAME }
