environment:
  global:
    WEBOTS_HOME_PROTECTED: "/C/projects/webots"
    WEBOTS_HOME: "C:\\projects\\webots"
    VISUAL_STUDIO_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio 10.0"
    INNO_SETUP_HOME: "C:\\Program Files (x86)\\Inno Setup 6"
#    PYTHON37_HOME: "C:\\Python37-x64"
#    PYTHON27_HOME: "C:\\Python27-x64"
#    JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
#    PATH: "C:\\Python27-x64;C:\\Python27-x64\\Scripts;C:\\msys64\\mingw64\\bin;C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin;C:\\Program Files\\Java\\jdk1.8.0\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;%PATH%"

  matrix:
    - compiler: msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64

install:
  - C:\\msys64\\usr\\bin\\pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
  - C:\\msys64\\usr\\bin\\pacman --noconfirm -S --noconfirm git mingw-w64-x86_64-cppcheck cmake
  - pip install -r %APPVEYOR_BUILD_FOLDER%/tests/sources/requirements.txt
  - pip install -r %APPVEYOR_BUILD_FOLDER%/docs/tests/requirements.txt
  - C:\\msys64\\usr\\bin\\bash --login -c "cd %WEBOTS_HOME_PROTECTED%; git submodule init; git submodule update"
  - C:\\msys64\\usr\\bin\\bash --login -c "%WEBOTS_HOME_PROTECTED%/src/install_scripts/msys64_installer.sh --all"
  - C:\\msys64\\usr\\bin\\bash --login -c "echo export JAVA_HOME=\\\"/C/Program\ Files/Java/jdk1.8.0\\\" >> ~/.bash_profile"
  - C:\\msys64\\usr\\bin\\bash --login -c "echo export PYTHON27_HOME=/C/Python27-x64 >> ~/.bash_profile"
  - C:\\msys64\\usr\\bin\\bash --login -c "echo export PYTHON37_HOME=/C/Python37-x64 >> ~/.bash_profile"
  - C:\\msys64\\usr\\bin\\bash --login -c "echo export VISUAL_STUDIO_PATH=\\\"/C/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio\ 10.0\\\" >> ~/.bash_profile"
  - C:\\msys64\\usr\\bin\\bash --login -c "echo export INNO_SETUP_HOME=\\\"/C/Program\ Files\ \(x86\)/Inno\ Setup\ 6\\\" >> ~/.bash_profile"
  - C:\\msys64\\usr\\bin\\bash --login -c "echo export PATH=\"$PYTHON37_HOME:$PYTHON37_HOME/Scripts:/C/msys64/mingw64/bin:/mingw64/bin:/usr/bin:$JAVA_HOME/bin:/c/WINDOWS/system32:/c/WINDOWS:$MATLAB_HOME/bin\" >> ~/.bash_profile"
  - C:\\msys64\\usr\\bin\\bash --login -c "cat ~/.bash_profile"
  - C:\\msys64\\usr\\bin\\bash --login -c "env"
  - C:\\msys64\\usr\\bin\\bash --login -c "python --version"
  - C:\\msys64\\usr\\bin\\bash --login -c "cd %WEBOTS_HOME_PROTECTED%; make distrib -j4"

build: off

test_script:
  - C:\\msys64\\usr\\bin\\bash --login -c "python -m unittest discover -s %WEBOTS_HOME_PROTECTED%/docs/tests"
  - ps: if ($env:APPVEYOR_SCHEDULED_BUILD -ne "True" -and $env:APPVEYOR_REPO_TAG -ne "true") { C:\\Python37-x64\\python.exe $env:WEBOTS_HOME\\tests\\sources\\generate_diff.py $env:APPVEYOR_REPO_COMMIT $env:APPVEYOR_REPO_NAME }
  - C:\\msys64\\usr\\bin\\bash --login -c "python -m unittest discover -s %WEBOTS_HOME_PROTECTED%/tests/sources"
