# This file is used by the "webots-tag" appveyor project, it is identical to the .appveyor-build.yml file,
# except for the first instruction: skip_non_tags: true

branches:
  # this rule applies both to branch and tag names
  except:
    - /nightly_.*/

skip_non_tags: true

clone_depth: 1

init:
  # The following line will display the login information for a remote desktop connection (useful to debug)
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;C:\msys64\usr\bin;%PATH%
  - pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
  - pacman --noconfirm -Syuu
  - echo export WEBOTS_HOME="%APPVEYOR_BUILD_FOLDER%" >> C:\msys64\home\appveyor\.bash_profile
  - type %APPVEYOR_BUILD_FOLDER%\src\install_scripts\bash_profile.appveyor >> C:\msys64\home\appveyor\.bash_profile
  - bash --login -c "cd $WEBOTS_HOME_PATH; git submodule init; git submodule update"
  - bash --login -c "$WEBOTS_HOME_PATH/src/install_scripts/msys64_installer.sh --all"
  - bash --login -c "$WEBOTS_HOME_PATH/src/install_scripts/nodejs_windows_installer.sh"
  - bash --login -c "$WEBOTS_HOME_PATH/src/install_scripts/inno_setup_installer.sh"
  - python -m pip install --upgrade pip
  - pip install PyGithub
  # The following line make the session on the virtual machine last some time to allow remote desktop session debugging
  - ps: Start-Sleep -s 3600

build_script:
  - set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;C:\msys64\usr\bin;%PATH%
  - set WEBOTS_HOME=%APPVEYOR_BUILD_FOLDER%
  - ps: if ($env:APPVEYOR_REPO_TAG -ne "true") { python $env:APPVEYOR_BUILD_FOLDER\src\packaging\set_commit_and_date_in_version.py $env:APPVEYOR_REPO_COMMIT }
  - bash --login -c "cd $WEBOTS_HOME_PATH; make distrib -j4"
  - python %APPVEYOR_BUILD_FOLDER%\src\packaging\publish_release.py --key=%GITHUB_API_KEY% --repo=%APPVEYOR_REPO_NAME% --branch=%APPVEYOR_REPO_BRANCH% --commit=%APPVEYOR_REPO_COMMIT% --tag=%APPVEYOR_REPO_TAG_NAME%
