environment:
  global:
    WEBOTS_HOME: "C:\\projects\\webots"

  matrix:
    - compiler: msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      #PATH: "C:\\msys64\\%MSYSTEM%\\bin;C:\\msys64\\usr\\bin;%PATH%"
      PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x" # currently 3.4.3
      PYTHON_ARCH: "64"
    
install:
  - C:\\msys64\\usr\\bin\\pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
  - C:\\msys64\\usr\\bin\\pacman --noconfirm -S --noconfirm mingw-w64-x86_64-cppcheck
#  - C:\\msys64\\usr\\bin\\bash.exe --login -c "update-core"
#  - C:\\msys64\\usr\\bin\\msys2_shell.bat --login -c pacman -S --noconfirm mingw-w64-x86_64-cppcheck
#  - bash -lc "pacman --noconfirm --sync --refresh --refresh pacman"
#  - bash -xlc "pacman -S --noconfirm mingw-w64-x86_64-cppcheck"
  - pip install -r %APPVEYOR_BUILD_FOLDER%/tests/sources/requirements.txt
  - pip install -r %APPVEYOR_BUILD_FOLDER%/docs/tests/requirements.txt
  
build_script:
  - python --version
  - C:\\msys64\\usr\\bin\\bash --login -c "ls"
  - C:\\msys64\\usr\\bin\\bash --login -c "echo $(PWD)"
  
test_script:
  - C:\\msys64\\usr\\bin\\bash --login -c "python -m unittest discover -s C:\\projects\\webots\\docs\\tests"
  - C:\\msys64\\usr\\bin\\bash --login -c "python -m unittest discover -s C:\\projects\\webots\\tests\\sources"
