environment:
  global:
    WEBOTS_HOME_PROTECTED: "/C/projects/webots"
    WEBOTS_HOME: "C:\\projects\\webots"

  matrix:
    - compiler: msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64

install:
  - C:\\msys64\\usr\\bin\\pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
  - C:\\msys64\\usr\\bin\\pacman --noconfirm -S --noconfirm mingw-w64-x86_64-cppcheck mingw-w64-x86_64-clang
  - pip install -r %APPVEYOR_BUILD_FOLDER%/tests/sources/requirements.txt
  - pip install -r %APPVEYOR_BUILD_FOLDER%/docs/tests/requirements.txt

build_script:
  - python --version
  - python --version  # The 'build_script' step is mandatory

test_script:
  - C:\\msys64\\usr\\bin\\bash --login -c "echo $WEBOTS_HOME"
  - C:\\msys64\\usr\\bin\\bash --login -c "echo $WEBOTS_HOME_PROTECTED"
  - C:\\msys64\\usr\\bin\\bash --login -c "echo $APPVEYOR_BUILD_FOLDER"
  - C:\\msys64\\usr\\bin\\bash --login -c "python -m unittest discover -s %WEBOTS_HOME_PROTECTED%/docs/tests"
  - C:\\msys64\\usr\\bin\\bash --login -c "python -m unittest discover -s %WEBOTS_HOME_PROTECTED%/tests/sources"
