blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/cyberbotics/webots/tree/released/docs
    about: Fix or improve the Webots user guide, reference or automobile manual.
  - name: GitHub Discussions
    url: https://github.com/cyberbotics/webots/discussions/new
    about: Ask a question or request a new feature in Webots
  - name: Robotics StackExchange
    url: https://robotics.stackexchange.com
    about: Ask technical questions (be sure to use the 'webots' tag).
  - name: Discord Server
    url: https://discordapp.com/invite/nTWbN9m
    about: Chat about Webots and read news.
