version: "3.8"

services:

  webots:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FROM_IMAGE=$IMAGE
        - PROJECT_PATH=$PROJECT_PATH
        - MAKE=$MAKE
    command: $WEBOTS
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=$XAUTH
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - '$PORT:$PORT'
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - ${XAUTH:-/dev/null}:${XAUTH:-/dev/null}
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
