name: Test Suite macOS

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  schedule:
    - cron:  '0 23 * * *'
  push:
    tags:
      - '*'

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@v0.3.0
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  build:
    needs: cleanup-runs
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || contains(github.event.pull_request.labels.*.name, 'test distribution') || contains(github.event.pull_request.labels.*.name, 'test suite') || contains(github.event.pull_request.labels.*.name, 'test world update') }}
    strategy:
      matrix:
        os: [macos-11]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
         submodules: true
         fetch-depth: 15
    - name: Install Webots Compilation Dependencies
      run: |
        brew install swig wget cmake python@3.7 python@3.8 python@3.9 python@3.10
        npm install -g appdmg
        # install regular Python 3.7
        wget -qq https://www.python.org/ftp/python/3.7.9/python-3.7.9-macosx10.9.pkg
        sudo installer -pkg python-3.7.9-macosx10.9.pkg -target /
        # install regular Python 3.8
        wget -qq https://www.python.org/ftp/python/3.8.10/python-3.8.10-macos11.pkg
        sudo installer -pkg python-3.8.10-macos11.pkg -target /
        # install regular Python 3.9
        wget -qq https://www.python.org/ftp/python/3.9.12/python-3.9.12-macos11.pkg
        sudo installer -pkg python-3.9.12-macos11.pkg -target /
        # install regular Python 3.10
        wget -qq https://www.python.org/ftp/python/3.10.4/python-3.10.4-macos11.pkg
        sudo installer -pkg python-3.10.4-macos11.pkg -target /
    - name: Set Commit SHA in Version
      if: ${{ github.event_name == 'schedule' }}
      run: python scripts/packaging/set_commit_and_date_in_version.py $(git log -1 --format='%H')
    - name: Webots Package Creation
      run: |
        export JAVA_HOME="$(/usr/libexec/java_home -v 16)"
        export PATH=/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin/:$PATH
        make distrib -j4
    - name: Prepare Webots Controller Deployment
      if: ${{ github.event_name == 'schedule' || contains(github.event.pull_request.labels.*.name, 'deploy libcontroller') }}
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.WEBOTS_CONTROLLER_DEPLOY_KEY }}
    - name: Deploy Webots Controller
      if: ${{ github.event_name == 'schedule' || contains(github.event.pull_request.labels.*.name, 'deploy libcontroller') }}
      run: scripts/packaging/sync_controller_lib.sh
    - name: Create/Update GitHub release
      if: ${{ (github.event_name == 'push' || github.event_name == 'schedule') }}
      run: |
        sudo python -m pip install requests PyGithub
        scripts/packaging/publish_release.py --key=${{ secrets.GITHUB_TOKEN }} --repo=${{ github.repository }} --branch=${{ github.ref }} --commit=$(git log -1 --format='%H') --tag=${{ github.ref }}
    - uses: actions/upload-artifact@v2
      if: ${{ contains(github.event.pull_request.labels.*.name, 'test suite') || contains(github.event.pull_request.labels.*.name, 'test distribution') }}
      with:
        name: build-${{ matrix.os }}
        path: |
          distribution/*.dmg
  test-suite:
    needs: build
    if: ${{ contains(github.event.pull_request.labels.*.name, 'test suite') }}
    strategy:
      matrix:
        os: [macos-11]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-${{ matrix.os }}
        path: artifact
    - name: Extract Webots
      run: |
        hdiutil mount artifact/webots-*.dmg
        sudo cp -R /Volumes/Webots/Webots.app /Applications
        hdiutil unmount /Volumes/Webots
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Test
      run:
        export WEBOTS_DISABLE_SAVE_SCREEN_PERSPECTIVE_ON_CLOSE=true
        export WEBOTS_HOME=/Applications/Webots.app
        # we currently can't run the test suite because of https://github.com/cyberbotics/webots/issues/2110
        # python tests/test_suite.py
  delete-artifacts:
    needs: [build, test-suite]
    if: ${{ always() && !contains(github.event.pull_request.labels.*.name, 'test distribution') }}
    strategy:
      matrix:
        os: [macos-11]
    runs-on: ubuntu-latest
    steps:
    - name: Delete artifacts
      uses: geekyeggo/delete-artifact@v1
      with:
        name: build-${{ matrix.os }}
